baseURL = "http://walves.blog.br/"
languageCode = "pt-br"
title = "Wllyssys Alves"
theme = "cactus"
copyright = "Wllyssys Alves" # cactus will use title if copyright is not set
disqusShortname = "example" # Used when comments is enabled. Cactus will use site title if not set
# googleAnalytics = "UA-1234-5"

publishDir = "docs"


# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Início"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/posts"
weight = 2

[[menu.main]]
name = "Wiki"
url = "/wiki"
weight = 3

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4

[params]

  colortheme = "white" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  showAllPostsArchive = false # default

  # Home page settings
  description = "Trabalhando no Banco do Brasil e estudando Ciência de Dados. Este local surgiu inspirado nas ideias da comunidade [IndieWeb](https://indieweb.org/) e [Digital Garden](https://maggieappleton.com/garden-history/)."
  mainSection = "posts" # your main section
  mainSectionTitle = "Blog"
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = false # show tags overview by default.
  showProjectsList = false # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/gohugoio" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = true # default
  showReadTime = false # default

  [params.comments]
    enabled = false # default
    engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "email"
    link = "ulima69@gmail.com"  # no need for "mailto:" in the head
